/* global tailwind */
tailwind.config = {
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface':                    '#0c1324',
        'surface-dim':                '#0c1324',
        'surface-bright':             '#33394c',
        'surface-container-lowest':   '#070d1f',
        'surface-container-low':      '#151b2d',
        'surface-container':          '#191f31',
        'surface-container-high':     '#23293c',
        'surface-container-highest':  '#2e3447',
        'on-surface':                 '#dce1fb',
        'on-surface-variant':         '#c5c6cd',
        'inverse-surface':            '#dce1fb',
        'inverse-on-surface':         '#2a3043',
        'outline':                    '#8f9097',
        'outline-variant':            '#45474c',
        'surface-tint':               '#bcc7de',
        'primary':                    '#bcc7de',
        'on-primary':                 '#263143',
        'primary-container':          '#1e293b',
        'on-primary-container':       '#8590a6',
        'inverse-primary':            '#545f73',
        'secondary':                  '#ffb874',
        'on-secondary':               '#4b2800',
        'secondary-container':        '#e78603',
        'on-secondary-container':     '#522c00',
        'on-secondary-fixed':         '#2d1600',
        'tertiary':                   '#4edea3',
        'on-tertiary':                '#003824',
        'tertiary-container':         '#00301e',
        'on-tertiary-container':      '#00a472',
        'error':                      '#ffb4ab',
        'on-error':                   '#690005',
        'error-container':            '#93000a',
        'on-error-container':         '#ffdad6',
        'background':                 '#0c1324',
        'on-background':              '#dce1fb',
        'surface-variant':            '#2e3447',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg':      '0.5rem',
        'xl':      '0.75rem',
        'full':    '9999px',
      },
      spacing: {
        'xs':             '4px',
        'sm':             '12px',
        'base':           '8px',
        'md':             '24px',
        'lg':             '40px',
        'xl':             '64px',
        'gutter':         '24px',
        'margin-mobile':  '16px',
        'margin-desktop': '32px',
      },
      fontFamily: {
        'display-lg':  ['Geist', 'sans-serif'],
        'headline-lg': ['Geist', 'sans-serif'],
        'headline-md': ['Geist', 'sans-serif'],
        'headline-sm': ['Geist', 'sans-serif'],
        'label-md':    ['Geist', 'sans-serif'],
        'mono-data':   ['Geist', 'monospace'],
        'body-lg':     ['Inter', 'sans-serif'],
        'body-md':     ['Inter', 'sans-serif'],
        'body-sm':     ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg':          ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg':         ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md':         ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-sm':         ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-sm-mobile':  ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'body-lg':             ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md':             ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm':             ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md':            ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'mono-data':           ['14px', { lineHeight: '20px', fontWeight: '500' }],
      },
    },
  },
};
